server.py
* Hardware:
* Toolchain:
* SDK:
=> Country post and country get by id endpoints complete

models.py, server.py
* Hardware:
* Toolchain:
* SDK:
=> PUT endpoint for countries

models.py
changed nationality nullable to true
- [X ] New feature (non-breaking change which adds functionality)
* Hardware:
* Toolchain:
* SDK:
- [X ] I have performed a self-review of my own code
- [X ] My changes generate no new warnings
=> added home country to users

models.py, server.py
There were duplicates and bugs from the last merge that were throwing errors when starting the server. Server is running now
* Hardware:
* Toolchain:
* SDK:
=> BUG fixes in models and server, server running

models.py, server.py
Created GET mapview endpoing, Consolidated mapview and users/countries endpoints, Updated CountrySchema to include code column, commented out country_code field in users_countries_join. I don't think this is a valid way to join, need to use relationships.
Tested in postman, server runs without errors in models and server files
* Hardware:
* Toolchain:
* SDK:
=> GET mapview, changes to UserCountry Schema, minor bug fixes

models.py, scratch-and-map-front-end/package.json, scratch-and-map-front-end/src/Auth/Auth.js, scratch-and-map-front-end/src/Auth/FbLogin.js, scratch-and-map-front-end/yarn.lock, server.py
* Hardware:
* Toolchain:
* SDK:
=> Ryan matthews

seed_files/COUNTRY_DATA.csv
* Hardware:
* Toolchain:
* SDK:
=> Country info seed data added

models.py, server.py
Updated marshamllow schema which allows GET users/id to return array of mapview objects by user id. Organized code for readability. Created GET(all) mapview endpoint, but it's buggy and we might not need it. The next step is to get it testing properly, but for now, all other endpoints are testing out in Postman.
* Hardware:
* Toolchain:
* SDK:
=> Users endpoint returns array of mapview objects

seed.py
* Hardware:
* Toolchain:
* SDK:
=> Modified seed.py to include country_code

scratch-and-map-front-end/src/components/MapContainer/MapContainer.js, scratch-and-map-front-end/yarn.lock
* Hardware:
* Toolchain:
* SDK:
=> Styling updates and changed map tile in front end

models.py, scratch-and-map-front-end/src/Auth/FbLogin.js, scratch-and-map-front-end/yarn.lock, server.py
Bug fixes in countries schema, modify FB login
* Hardware:
* Toolchain:
* SDK:
=> Bug fixes, changes to sdk

scratch-and-map-front-end/src/Auth/FbLogin.js
Fix login bugs to render w/o cors issues
* Hardware:
* Toolchain:
* SDK:
=> FRONT/FIX : fix fblogin bugs

scratch-and-map-front-end/src/Auth/FbLogin.js
* Hardware:
* Toolchain:
* SDK:
=> fix missing brace on line 27

scratch-and-map-front-end/public/_redirects
* Hardware:
* Toolchain:
* SDK:
=> fixing redirects file

README.md
updated readme template. Will add logo once selected.
- [ X] This change requires a documentation update
* Hardware:
* Toolchain:
* SDK:
- [ X] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [X ] My changes generate no new warnings
=> updated readme template

seed_files/COUNTRY_DATA.csv
* Hardware:
* Toolchain:
* SDK:
=> Updated country seed data

scratch-and-map-front-end/src/components/MapContainer/MapContainer.js
Added country name pop ups on mouse over.  
* Hardware:
* Toolchain:
* SDK:
=> Added country name pop ups on mouse over

scratch-and-map-front-end/src/components/MapContainer/MapContainer.js
Clicking a country stores the country code in state
* Hardware:
* Toolchain:
* SDK:
=> Clicking a country stores the country code in state

scratch-and-map-front-end/src/components/helper.js
* Hardware:
* Toolchain:
* SDK:
=> Added helper file for front end country info

scratch-and-map-front-end/src/components/MapContainer/MapContainer.js
made country name popups pop up from mouse position
* Hardware:
* Toolchain:
* SDK:
=> made country name popups pop up from mouse position

models.py, server.py
* Hardware:
* Toolchain:
* SDK:
=> reverting changes to countries_join data

server.py
create GET endpoint for all countries
Tested in Postman, returns all countries and travelers that have a status in those countries
* Hardware:
* Toolchain:
* SDK:
=> created GET all countries endpoint in server.py

scratch-and-map-front-end/src/components/helper.js
* Hardware:
* Toolchain:
* SDK:
=> Added helper function to convert back end country id to country code

dbCreate.py, models.py, requirements.txt, seed.py, seed_files/MOCK_DATA.csv
* Hardware:
* Toolchain:
* SDK:
=> add dbcreate and update seed files.

scratch-and-map-front-end/public/index.html, scratch-and-map-front-end/src/App.js, scratch-and-map-front-end/src/components/SideBar.js
Set up sidebar component
Tested in Postman, returns all countries and travelers that have a status in those countries
- [] Postman
* Hardware:
* Toolchain:
* SDK:
=> Side Bar Component

scratch-and-map-front-end/src/actions/mapActions.js, scratch-and-map-front-end/src/components/MapContainer/MapContainer.js, scratch-and-map-front-end/src/index.js, scratch-and-map-front-end/src/reducers/mapReducer.js, scratch-and-map-front-end/src/reducers/rootReducer.js
set up redux file structure, and basic implementation on MapContainer
* Hardware:
* Toolchain:
* SDK:
=> set up redux file structure, and basic implementation on MapContainer

scratch-and-map-front-end/src/Auth/Auth.js, scratch-and-map-front-end/src/Auth/FbLogin.js, scratch-and-map-front-end/src/components/LandingPage.js, scratch-and-map-front-end/src/index.scss
* Hardware:
* Toolchain:
* SDK:
=> Beginning landing page code

scratch-and-map-front-end/src/actions/mapActions.js, scratch-and-map-front-end/src/components/MapContainer/MapContainer.js
Cleaned up mapContainer code
* Hardware:
* Toolchain:
* SDK:
=> Brandon moll

seed.py, seed_files/MOCK_DATA.csv
* Hardware:
* Toolchain:
* SDK:
=> Updated seed.py and mock data with fb_access_token

scratch-and-map-front-end/src/components/MapContainer/MapContainer.js
* Hardware:
* Toolchain:
* SDK:
=> fix import bug

scratch-and-map-front-end/src/components/AuthContainer/Auth.js, scratch-and-map-front-end/src/components/NavContainer/NavBar.js, scratch-and-map-front-end/src/index.scss
* Hardware:
* Toolchain:
* SDK:
=> Landing and map pages responsive

scratch-and-map-front-end/src/components/MapContainer/MapContainer.js
* Hardware:
* Toolchain:
* SDK:
=> fix typo in user get statement in mapcontainer

scratch-and-map-front-end/src/App.js, scratch-and-map-front-end/src/components/Loading.js
* Hardware:
* Toolchain:
* SDK:
=> Updated app.js

scratch-and-map-front-end/src/components/Loading.js, scratch-and-map-front-end/src/components/MapContainer/Legend.js, scratch-and-map-front-end/src/components/MapContainer/MapContainer.js, scratch-and-map-front-end/src/components/NavContainer/NavBar.js, scratch-and-map-front-end/src/index.scss
* Hardware:
* Toolchain:
* SDK:
=> Added Legend Component

scratch-and-map-front-end/src/components/MapContainer/MapContainer.js
added Loading ternary to mapContainer
* Hardware:
* Toolchain:
* SDK:
=> added Loading ternary to mapContainer

scratch-and-map-front-end/src/components/AuthContainer/Auth.js, scratch-and-map-front-end/src/components/AuthContainer/FbLogin.js, scratch-and-map-front-end/src/components/MapContainer/CardSlider.js, scratch-and-map-front-end/src/components/MapContainer/MapContainer.js, scratch-and-map-front-end/src/components/NavContainer/NavBar.js, scratch-and-map-front-end/src/index.scss
* Hardware:
* Toolchain:
* SDK:
=> Working on redirect to map

scratch-and-map-front-end/src/components/AuthContainer/FbLogin.js, server.py
Cleaned up Facebook username
- [X ] Bug fix (non-breaking change which fixes an issue)
* Hardware:
* Toolchain:
* SDK:
=> Added login Functionality

scratch-and-map-front-end/src/components/MapContainer/Card.js, scratch-and-map-front-end/src/components/MapContainer/CardSlider.js, scratch-and-map-front-end/src/components/MapContainer/MapContainer.js, server.py
* Hardware:
* Toolchain:
* SDK:
=> allow for the saving/posting/putting of data from the map

scratch-and-map-front-end/src/components/MapContainer/Card.js, scratch-and-map-front-end/src/components/MapContainer/CardSlider.js
* Hardware:
* Toolchain:
* SDK:
=> Card to flex display

scratch-and-map-front-end/src/components/AuthContainer/FbLogin.js, scratch-and-map-front-end/src/components/MapContainer/Card.js
* Hardware:
* Toolchain:
* SDK:
=> fix localStorage get and set bugs

scratch-and-map-front-end/src/components/MapContainer/MapContainer.js
* Hardware:
* Toolchain:
* SDK:
=> Removed second loader from mapcontainer

scratch-and-map-front-end/src/components/MapContainer/Card.js, scratch-and-map-front-end/src/index.scss
added capital
added language
* Hardware:
* Toolchain:
* SDK:
=>  added styling to card added currency

scratch-and-map-front-end/src/components/MapContainer/Card.js
* Hardware:
* Toolchain:
* SDK:
=> Fixed missing </div> in card

models.py, scratch-and-map-front-end/src/App.js, scratch-and-map-front-end/src/components/AuthContainer/FbLogin.js, seed.py, seed_files/MOCK_DATA.csv, server.py
* Hardware:
* Toolchain:
* SDK:
=> make sure proper data is passed into put in fb login

scratch-and-map-front-end/src/components/MapContainer/Card.js, scratch-and-map-front-end/src/index.scss, scratch-and-map-front-end/src/styles/card.scss
* Hardware:
* Toolchain:
* SDK:
=> Country card mobile responsive and flags corrected

scratch-and-map-front-end/src/App.js, scratch-and-map-front-end/src/components/AuthContainer/FbLogin.js
changed endpoint in app.js to include token
updated FB login Response to res from From axios call"
"
* Hardware:
* Toolchain:
* SDK:
=> removed http from axios call in app.js

server.py
Updated broken mapview endpoint, now able to update mapview by user_id rather than id
* Hardware:
* Toolchain:
* SDK:
=> PUT for mapview, able to update by user_id

scratch-and-map-front-end/src/components/NavContainer/DevCard.js, scratch-and-map-front-end/src/components/NavContainer/NavBar.js, scratch-and-map-front-end/src/components/NavContainer/ParentNav.js, scratch-and-map-front-end/src/index.scss
* Hardware:
* Toolchain:
* SDK:
=> Added Dev Team Modal

scratch-and-map-front-end/src/components/NavContainer/FriendListView.js, server.py
* Hardware:
* Toolchain:
* SDK:
=> fixed PUT /mapview, updates by user_id and country_id

scratch-and-map-front-end/src/components/NavContainer/FriendListView.js, scratch-and-map-front-end/src/components/SideBar.js
* Hardware:
* Toolchain:
* SDK:
=> redo filter functionality

scratch-and-map-front-end/src/components/NavContainer/DevCard.js, scratch-and-map-front-end/src/index.scss, scratch-and-map-front-end/src/styles/dest/App.css
* Hardware:
* Toolchain:
* SDK:
=> added styling for about us page

scratch-and-map-front-end/src/components/MapContainer/Card.js, scratch-and-map-front-end/src/components/helper.js, scratch-and-map-front-end/src/index.scss
* Hardware:
* Toolchain:
* SDK:
=> Cards showing if other travlers set status for given country

scratch-and-map-front-end/src/components/MapContainer/Card.js, scratch-and-map-front-end/src/components/NavContainer/FriendListView.js, scratch-and-map-front-end/src/index.scss
* Hardware:
* Toolchain:
* SDK:
=> UI: Friend Buttons and SearchBar in Sidebar, Updated  PUT endpoint in Card.js

scratch-and-map-front-end/src/components/MapContainer/Card.js, scratch-and-map-front-end/src/components/NavContainer/NavBar.js, scratch-and-map-front-end/src/index.scss, scratch-and-map-front-end/src/styles/dest/App.css
* Hardware:
* Toolchain:
* SDK:
=> contact us module is responsive

scratch-and-map-front-end/src/components/NavContainer/FriendListView.js, scratch-and-map-front-end/src/index.scss
* Hardware:
* Toolchain:
* SDK:
=>  FriendsList scroll updated responsiveness

scratch-and-map-front-end/src/index.scss, server.py
* Hardware:
* Toolchain:
* SDK:
=> PUT updates persist

scratch-and-map-front-end/src/components/NavContainer/NavBar.js
* Hardware:
* Toolchain:
* SDK:
=> Corrected log in modal

scratch-and-map-front-end/src/components/MapContainer/Card.js, scratch-and-map-front-end/src/components/MapContainer/MapContainer.js, scratch-and-map-front-end/src/components/NavContainer/NavBar.js
* Hardware:
* Toolchain:
* SDK:
=> Changed how MapContainer gets user info in order to render friends maps

models.py
* Hardware:
* Toolchain:
* SDK:
=> BACK : user_id returning in travelers

scratch-and-map-front-end/src/components/NavContainer/FriendListView.js
* Hardware:
* Toolchain:
* SDK:
=> Friends don't display unless user is logged in

scratch-and-map-front-end/src/components/Landing.js, scratch-and-map-front-end/src/index.scss
* Hardware:
* Toolchain:
* SDK:
=> Blurb added to landing page

scratch-and-map-front-end/src/components/MapContainer/Card.js, scratch-and-map-front-end/src/components/MapContainer/MapContainer.js, scratch-and-map-front-end/src/components/helper.js
* Hardware:
* Toolchain:
* SDK:
=> Edge cases solved and notes rendering

scratch-and-map-front-end/src/components/NavContainer/NavBar.js, scratch-and-map-front-end/src/components/NavContainer/ParentNav.js, scratch-and-map-front-end/src/index.scss
Logout Button toggles with Sign Up and Log Out Buttons. When a user is logged in, they see a logout button, however when not logged in, they see The Signup and Login Buttons.
* Hardware:
* Toolchain:
* SDK:
=> Logout Button

scratch-and-map-front-end/package.json, scratch-and-map-front-end/src/index.scss, scratch-and-map-front-end/yarn.lock
* Hardware:
* Toolchain:
* SDK:
=>  fixed premium button issue

scratch-and-map-front-end/public/index.html, scratch-and-map-front-end/src/components/NavContainer/DevCard.js
* Hardware:
* Toolchain:
* SDK:
=> Cleanup Time: Addressed console errors and warnings for DevCard.js

scratch-and-map-front-end/src/components/MapContainer/Card.js, scratch-and-map-front-end/src/components/MapContainer/MapContainer.js
fixed error being thrown when clicking outside an open country card
* Hardware:
* Toolchain:
* SDK:
=> fixed error being thrown when clicking outside an open country card

scratch-and-map-front-end/src/components/Landing.js, scratch-and-map-front-end/src/index.scss
* Hardware:
* Toolchain:
* SDK:
=> Blurb on landing page responsive

scratch-and-map-front-end/src/components/NavContainer/DevCard.js, scratch-and-map-front-end/src/components/NavContainer/NavBar.js
* Hardware:
* Toolchain:
* SDK:
=> Cleaned up NavBar.js console errors, adjusted text on my avatar info to fit

scratch-and-map-front-end/public/manifest.json, scratch-and-map-front-end/src/components/AuthContainer/FbLogin.js
* Hardware:
* Toolchain:
* SDK:
=> Added missing /

scratch-and-map-front-end/src/components/AuthContainer/FbLogin.js
fixes to signup api call
* Hardware:
* Toolchain:
* SDK:
=> fixes to signup api call

scratch-and-map-front-end/src/App.js, scratch-and-map-front-end/src/components/Landing.js, scratch-and-map-front-end/src/index.scss, scratch-and-map-front-end/yarn.lock
* Hardware:
* Toolchain:
* SDK:
=> styled blurb on landing page

scratch-and-map-front-end/src/components/AuthContainer/Auth.js, scratch-and-map-front-end/src/components/AuthContainer/FbLogin.js, scratch-and-map-front-end/src/components/AuthContainer/Login.js, scratch-and-map-front-end/src/components/CheckoutForm.js, scratch-and-map-front-end/src/components/Landing.js, scratch-and-map-front-end/src/components/Loading.js, scratch-and-map-front-end/src/components/MapContainer/Card.js, scratch-and-map-front-end/src/components/MapContainer/CardSlider.js, scratch-and-map-front-end/src/components/MapContainer/FriendsTravel.js, scratch-and-map-front-end/src/components/MapContainer/Legend.js, scratch-and-map-front-end/src/components/MapContainer/MapContainer.js, scratch-and-map-front-end/src/components/NavContainer/NavBar.js
* Hardware:
* Toolchain:
* SDK:
=> Code Cleanup

server.py
cors error fix attempt.
* Hardware:
* Toolchain:
* SDK:
=> cors error fix attempt

scratch-and-map-front-end/.htaccess, scratch-and-map-front-end/src/components/AuthContainer/FbLogin.js, scratch-and-map-front-end/web.config, server.py
* Hardware:
* Toolchain:
* SDK:
=> another cors attempt

server.py
fixed token endpoint and deleted commented out stuff
* Hardware:
* Toolchain:
* SDK:
=> fixed token endpoint and deleted commented out stuff

scratch-and-map-front-end/src/App.js
removed isloggedin
* Hardware:
* Toolchain:
* SDK:
=> removed isloggedin

seed.py
* Hardware:
* Toolchain:
* SDK:
=> remove db create all from seed file

seed.py
* Hardware:
* Toolchain:
* SDK:
=> connect db to app in seed file

seed.py
* Hardware:
* Toolchain:
* SDK:
=> attempting to create app context for seed file

scratch-and-map-front-end/src/components/AuthContainer/FbLogin.js, scratch-and-map-front-end/src/components/NavContainer/ParentNav.js
* Hardware:
* Toolchain:
* SDK:
=> add reload functionality in the login and logout components

models.py, seed.py, server.py
* Hardware:
* Toolchain:
* SDK:
=> Changes to DB: removed auto_scratch, added premium 

README.md
* Hardware:
* Toolchain:
* SDK:
=> Fleshed out readme a bit more

dbCreate.py
* Hardware:
* Toolchain:
* SDK:
=> alter imports on dbCreate.py

scratch-and-map-front-end/src/components/AuthContainer/FbLogin.js
* Hardware:
* Toolchain:
* SDK:
=> adjusted refresh functionality to work properly

scratch-and-map-front-end/src/index.scss
* Hardware:
* Toolchain:
* SDK:
=> removed keyframe

scratch-and-map-front-end/src/components/NavContainer/NavBar.js
clicking my map takes you back to your own from a friends map
* Hardware:
* Toolchain:
* SDK:
=> clicking my map takes you back to your own from a friends map

scratch-and-map-front-end/src/actions/isLoggedInAction.js, scratch-and-map-front-end/src/components/AuthContainer/FbLogin.js, scratch-and-map-front-end/src/components/NavContainer/NavBar.js, scratch-and-map-front-end/src/components/NavContainer/ParentNav.js, scratch-and-map-front-end/src/reducers/loggedInReducer.js, scratch-and-map-front-end/src/reducers/rootReducer.js
Logging in will now set isLoggedIn in redux store to true, displaying the correct login/log out buttons when they should.  Facebook login is back to working correctly, welcoming the user.
* Hardware:
* Toolchain:
* SDK:
=> Connected login system to redux

scratch-and-map-front-end/src/actions/isLoggedInAction.js, scratch-and-map-front-end/src/actions/mapActions.js, scratch-and-map-front-end/src/components/AuthContainer/Auth.js, scratch-and-map-front-end/src/components/AuthContainer/FbLogin.js, scratch-and-map-front-end/src/components/MapContainer/Card.js, scratch-and-map-front-end/src/components/NavContainer/NavBar.js, scratch-and-map-front-end/src/components/NavContainer/ParentNav.js, scratch-and-map-front-end/src/reducers/loggedInReducer.js
* Hardware:
* Toolchain:
* SDK:
=> Map working without login functionality
